### ISSUE TITLE
[meta] Address remaining TAG review issues

### ISSUE THREAD

**Issue by alexshalamov** [w3c/ambient-light#43]
List of remaining issues for [ALS](https://github.com/w3ctag/design-reviews/issues/115) TAG review.

 - [x] There's only a single example and no linked explainer document that would provide deeper understanding of how the various bits get used together. I think this would be clarifying both for the reader and the authors.

 - [x] The example (singular?) doesn't show how to use the Permission API in conjunction with the Ambient Light API, which seems pretty critical to actual use.

 - [x] Still not seeing an explainer/examples document in the Github repo (https://github.com/w3c/ambient-light). Should I be looking elsewhere for those?
